services:
  db:
    container_name: db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  new_kicks_api:
    container_name: new_kicks_api
    build: ./backend
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_USERNAME: ${POSTGRES_USERNAME}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
      - gems:/usr/local/bundle
  
  new_kicks_fe:
    container_name: new_kicks_fe
    build: ./frontend
    depends_on:
      - new_kicks_api
    environment:
      - BASE_URL_KICKS_API=${BASE_URL_KICKS_API}
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  gems: